# Generated by Django 6.0.3 on 2026-03-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='source',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
